/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pei;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author uept42-user
 */
public class Atividades extends javax.swing.JFrame {
    private static String foiClicado_1 = "";
    private static String foiClicado_2 = "";
    private static String foiClicado_3 = "";
    private static String foiClicado_4 = "";
    Pei pei = Pei.getInstance(); 
    private int pontuacao;
    private String nome;
    private String emailUsuario;
    
    /**
     * Creates new form Atividades
     */
    public Atividades(String email) {
        initComponents();
        this.emailUsuario = email;
        this.pontuacao = pei.buscarPontuacaoDoBanco(email); 
        this.nome = pei.buscarNomeDoBanco(email);
        nomeperfil.setText(String.valueOf(this.nome));
        pontos.setText(String.valueOf(this.pontuacao));
        foiClicado_1 = pei.buscarAtividade1DoBanco(email);
        foiClicado_2 = pei.buscarAtividade2DoBanco(email);
        foiClicado_3 = pei.buscarAtividade3DoBanco(email);
        foiClicado_4 = pei.buscarAtividade4DoBanco(email);
        if("sim".equals(String.valueOf(foiClicado_1))) {
            circulo1.setIcon(new ImageIcon(getClass().getResource("/images/Circulo verde.png")));
            texto1.setText("Resgatado");
            texto1.setForeground(new Color(0,178,128));
            atividade1.setEnabled(false);
        }
        if("sim".equals(String.valueOf(foiClicado_2))) {
            circulo2.setIcon(new ImageIcon(getClass().getResource("/images/Circulo verde.png")));
            texto2.setText("Resgatado");
            texto2.setForeground(new Color(0,178,128));
            atividade2.setEnabled(false);
        }
        if("sim".equals(String.valueOf(foiClicado_3))) {
            circulo3.setIcon(new ImageIcon(getClass().getResource("/images/Circulo verde.png")));
            texto3.setText("Resgatado");
            texto3.setForeground(new Color(0,178,128));
            atividade3.setEnabled(false);
        }
        if("sim".equals(String.valueOf(foiClicado_4))) {
            circulo4.setIcon(new ImageIcon(getClass().getResource("/images/Circulo verde.png")));
            texto4.setText("Resgatado");
            texto4.setForeground(new Color(0,178,128));
            atividade4.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pontos = new javax.swing.JLabel();
        nomeperfil = new javax.swing.JLabel();
        pontostxt = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        circulo4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        texto2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        texto4 = new javax.swing.JLabel();
        texto3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        circulo3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        circulo2 = new javax.swing.JLabel();
        circulo1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        atividade4 = new javax.swing.JButton();
        atividade3 = new javax.swing.JButton();
        atividade1 = new javax.swing.JButton();
        atividade2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 178, 128));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pontos.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        pontos.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(pontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, 40));

        nomeperfil.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        nomeperfil.setForeground(new java.awt.Color(255, 255, 255));
        nomeperfil.setText("Orquestra do Maestro");
        jPanel2.add(nomeperfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 21, -1, -1));

        pontostxt.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        pontostxt.setForeground(new java.awt.Color(255, 255, 255));
        pontostxt.setText("Pontos:");
        jPanel2.add(pontostxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/estrela.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, 43));

        jButton1.setBackground(new java.awt.Color(0, 178, 128));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/perfil config.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setDoubleBuffered(true);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, 60));

        jButton2.setBackground(new java.awt.Color(0, 178, 128));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log_menor_2.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 120));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Arvore.png"))); // NOI18N
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        circulo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Circulo.png"))); // NOI18N
        jPanel1.add(circulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 110, 100));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reciclagem.png"))); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 100));

        texto2.setText("+ 5 Pontos ");
        jPanel1.add(texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, 20));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homem andando.png"))); // NOI18N
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 100, 100));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mao dos ponto.png"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        texto4.setText("+ 20 Pontos ");
        jPanel1.add(texto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, -1, -1));

        texto3.setText("+ 10 Pontos ");
        jPanel1.add(texto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, -1, -1));

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(100, 100, 100));
        jLabel19.setText("<html>Informações de pontuação, tarefas<br> para adquirir tal pontuação</html>");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, -1, 30));

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(100, 100, 100));
        jLabel18.setText("<html>Informações de pontuação, tarefas<br> para adquirir tal pontuação</html>");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, 30));

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(100, 100, 100));
        jLabel20.setText("<html>Informações de pontuação, tarefas<br> para adquirir tal pontuação</html>");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, 40));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Reflorestamento");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, -1, 20));

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(100, 100, 100));
        jLabel17.setText("<html>Informações de pontuação, tarefas<br> para adquirir tal pontuação</html>");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 40));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Compostagem");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, 20));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("<html>Caminhada da <bR>conscientização<hmtl>");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 90, 30));

        texto1.setText("+ 20 Pontos ");
        jPanel1.add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        circulo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Circulo.png"))); // NOI18N
        jPanel1.add(circulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 110, 100));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Reciclagem");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        circulo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Circulo.png"))); // NOI18N
        jPanel1.add(circulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 130, 100));

        circulo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Circulo.png"))); // NOI18N
        jPanel1.add(circulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 130, 100));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("DESAFIOS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 25, -1, 28));

        atividade4.setBackground(new java.awt.Color(255, 255, 255));
        atividade4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atividade4ActionPerformed(evt);
            }
        });
        jPanel1.add(atividade4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 190, 230));

        atividade3.setBackground(new java.awt.Color(255, 255, 255));
        atividade3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atividade3ActionPerformed(evt);
            }
        });
        jPanel1.add(atividade3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 190, 230));

        atividade1.setBackground(new java.awt.Color(255, 255, 255));
        atividade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atividade1ActionPerformed(evt);
            }
        });
        jPanel1.add(atividade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 190, 230));

        atividade2.setBackground(new java.awt.Color(255, 255, 255));
        atividade2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atividade2ActionPerformed(evt);
            }
        });
        jPanel1.add(atividade2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 190, 230));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 450, 650));

        jButton6.setBackground(new java.awt.Color(0, 178, 128));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, 150, 70));

        jButton8.setBackground(new java.awt.Color(0, 178, 128));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reciclagem pequena.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 770, 150, 70));

        jButton7.setBackground(new java.awt.Color(0, 158, 128));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Plantinha.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 770, 150, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarLabelsPontos() {
        String pontosAtualizados = String.valueOf(pei.getPontos());
        pontos.setText(pontosAtualizados);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Perfil perfil = new Perfil(this.emailUsuario);
        perfil.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Pg1 pg1 = new Pg1(this.emailUsuario);
        pg1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Atividades atividades = new Atividades(this.emailUsuario);
        atividades.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Recompensa recompensa = new Recompensa(this.emailUsuario);
        recompensa.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void atividade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atividade1ActionPerformed
        if("não".equals(String.valueOf(foiClicado_1))) {
            int pontos_ganhos = 20;
            pei.GanharPontos(pontos_ganhos, this.emailUsuario);
            atualizarLabelsPontos();
            circulo1.setIcon(new ImageIcon(getClass().getResource("/images/Circulo verde.png")));
            texto1.setText("Resgatado");
            texto1.setForeground(new Color(0, 178, 128));
            atividade1.setEnabled(false);
            pei.atualizarAtividade1NoBanco(this.emailUsuario);
        } 
    }//GEN-LAST:event_atividade1ActionPerformed

    private void atividade2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atividade2ActionPerformed
        if("não".equals(String.valueOf(foiClicado_2))) {
            int pontos_ganhos = 5;
            pei.GanharPontos(pontos_ganhos, this.emailUsuario); // Passa o email do usuário
            atualizarLabelsPontos(); 
            circulo2.setIcon(new ImageIcon(getClass().getResource("/images/Circulo verde.png")));
            texto2.setText("Resgatado");
            texto2.setForeground(new Color(0, 178, 128));
            atividade2.setEnabled(false);
            pei.atualizarAtividade2NoBanco(this.emailUsuario);
        }
    }//GEN-LAST:event_atividade2ActionPerformed

    private void atividade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atividade3ActionPerformed
        if("não".equals(String.valueOf(foiClicado_3))) {
            int pontos_ganhos = 10;
            pei.GanharPontos(pontos_ganhos, this.emailUsuario); // Passa o email do usuário
            atualizarLabelsPontos(); 
            circulo3.setIcon(new ImageIcon(getClass().getResource("/images/Circulo verde.png")));
            texto3.setText("Resgatado");
            texto3.setForeground(new Color(0, 178, 128));
            atividade3.setEnabled(false);
            pei.atualizarAtividade3NoBanco(this.emailUsuario);
        } 
    }//GEN-LAST:event_atividade3ActionPerformed

    private void atividade4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atividade4ActionPerformed
        if("não".equals(String.valueOf(foiClicado_4))) {
            int pontos_ganhos = 20;
            pei.GanharPontos(pontos_ganhos, this.emailUsuario); // Passa o email do usuário
            atualizarLabelsPontos(); 
            circulo4.setIcon(new ImageIcon(getClass().getResource("/images/Circulo verde.png")));
            texto4.setText("Resgatado");
            texto4.setForeground(new Color(0, 178, 128));
            atividade4.setEnabled(false);
            pei.atualizarAtividade4NoBanco(this.emailUsuario);
        } 

    }//GEN-LAST:event_atividade4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Atividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Atividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Atividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Atividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Atividades("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atividade1;
    private javax.swing.JButton atividade2;
    private javax.swing.JButton atividade3;
    private javax.swing.JButton atividade4;
    private javax.swing.JLabel circulo1;
    private javax.swing.JLabel circulo2;
    private javax.swing.JLabel circulo3;
    private javax.swing.JLabel circulo4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nomeperfil;
    public javax.swing.JLabel pontos;
    private javax.swing.JLabel pontostxt;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    // End of variables declaration//GEN-END:variables
}
