/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pei;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author uept42-user
 */
public class Perfil extends javax.swing.JFrame {
    Pei pei = Pei.getInstance(); // Usando a instância única
    private static boolean foiClicado = false;
    private static boolean foiClicado_1 = false;
    private static boolean foiClicado_2 = false;
    private static boolean foiClicado_3 = false;
    /**
     * Creates new form Pg2
     */
    public Perfil() {
        initComponents();
        String ponto = String.valueOf(pei.getPontos());
        pontos.setText(ponto);
        if(foiClicado) {
            botao_seguir.setBackground(new Color(255,255,255));
            botao_seguir.setText("Seguindo");
            seguidores.setText("127");
        }
        if(foiClicado_1) {
            ImageIcon novo_icone = new ImageIcon(getClass().getResource("/images/euodeionetbeans.png"));
            curtida1.setIcon(novo_icone);
        }
        if(foiClicado_2) {
            ImageIcon novo_icone = new ImageIcon(getClass().getResource("/images/euodeionetbeans.png"));
            curtida3.setIcon(novo_icone);
        }
        if(foiClicado_3) {
            ImageIcon novo_icone = new ImageIcon(getClass().getResource("/images/euodeionetbeans.png"));
            curtida3.setIcon(novo_icone);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        seguidores = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        curtida1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        botao_seguir = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        curtida3 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        curtida2 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nomeperfil = new javax.swing.JLabel();
        pontos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pontostxt = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(0, 178, 128));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, 150, 70));

        jButton7.setBackground(new java.awt.Color(0, 178, 128));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Plantinha.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 770, 150, 70));

        jButton8.setBackground(new java.awt.Color(0, 178, 128));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reciclagem pequena.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setBorderPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 770, 150, 70));

        jScrollPane1.setBorder(null);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(445, 1600));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(445, 1600));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(445, 1600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(421, 1600));
        jPanel2.setPreferredSize(new java.awt.Dimension(398, 1650));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log_menor_2.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 37, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 63, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Orquetra do Maestro");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 37, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("publicações");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 94, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("seguidores");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 94, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/censura.png"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, 10));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(100, 100, 100));
        jLabel13.setText("10 min.");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, 20));
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 700, -1, 10));

        seguidores.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        seguidores.setForeground(new java.awt.Color(0, 0, 0));
        seguidores.setText("126");
        jPanel2.add(seguidores, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 63, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compartilhar.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, -1, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("eventos ativos");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 94, -1, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/censura.png"))); // NOI18N
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, 10));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fixo.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, -1, -1));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(100, 100, 100));
        jLabel14.setText("<html>\"Juntos, somos a mudança que o mundo precisa! ️💚 Traga seus tecidos e junte-se a nós na missão de reciclar e aquecer corações. #Sustentabilidade\"</html>");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 250, 100));

        curtida1.setBackground(new java.awt.Color(255, 255, 255));
        curtida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heart.png"))); // NOI18N
        curtida1.setBorder(null);
        curtida1.setBorderPainted(false);
        curtida1.setContentAreaFilled(false);
        curtida1.setDoubleBuffered(true);
        curtida1.setFocusPainted(false);
        curtida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curtida1ActionPerformed(evt);
            }
        });
        jPanel2.add(curtida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Postagem perfil 1.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 198, -1, -1));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("3");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 63, -1, -1));

        botao_seguir.setBackground(new java.awt.Color(0, 178, 128));
        botao_seguir.setForeground(new java.awt.Color(0, 0, 0));
        botao_seguir.setText("Seguir");
        botao_seguir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botao_seguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_seguirActionPerformed(evt);
            }
        });
        jPanel2.add(botao_seguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 132, 379, 31));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/retangulo_vazio.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 320, 420));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Postagem perfil 2.png"))); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 680, -1, -1));
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 730, -1, 10));
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 730, -1, 10));

        curtida3.setBackground(new java.awt.Color(255, 255, 255));
        curtida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heart.png"))); // NOI18N
        curtida3.setBorder(null);
        curtida3.setBorderPainted(false);
        curtida3.setContentAreaFilled(false);
        curtida3.setDoubleBuffered(true);
        curtida3.setFocusPainted(false);
        curtida3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curtida3ActionPerformed(evt);
            }
        });
        jPanel2.add(curtida3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1560, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compartilhar.png"))); // NOI18N
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 1560, -1, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fixo.png"))); // NOI18N
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 1560, -1, -1));

        jLabel32.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(100, 100, 100));
        jLabel32.setText("<html>\"\"Unidos, criamos um impacto positivo! 🌳💚 Traga seus tecidos e participe da nossa jornada de reciclagem e aquecimento de corações. #EcoConsciência #PlanetaMaisVerde #AçãoComPropósito\"\"</html>");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1410, 270, 100));

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(100, 100, 100));
        jLabel22.setText("5 dia");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 880, -1, 20));

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(100, 100, 100));
        jLabel23.setText("<html>\"\"Juntos, podemos transformar o mundo! 🌳💚<br> Contribua com seus tecidos e faça parte da nossa missão de reciclar e espalhar amor.<br> #SustentabilidadeEmAção #CuidarDoMeioAmbiente #TransformeComAmor\"</html>");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 920, 270, 100));

        curtida2.setBackground(new java.awt.Color(255, 255, 255));
        curtida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/heart.png"))); // NOI18N
        curtida2.setBorder(null);
        curtida2.setBorderPainted(false);
        curtida2.setContentAreaFilled(false);
        curtida2.setDoubleBuffered(true);
        curtida2.setFocusPainted(false);
        curtida2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curtida2ActionPerformed(evt);
            }
        });
        jPanel2.add(curtida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 1070, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compartilhar.png"))); // NOI18N
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 1070, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fixo.png"))); // NOI18N
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 1070, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/retangulo_vazio.png"))); // NOI18N
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 690, 320, 420));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Postagem perfil 3.png"))); // NOI18N
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 1170, -1, -1));

        jLabel30.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(100, 100, 100));
        jLabel30.setText("10 dia");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1370, -1, 20));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/retangulo_vazio.png"))); // NOI18N
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 1180, 320, 420));

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 120, 450, 650));

        jPanel1.setBackground(new java.awt.Color(0, 178, 128));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeperfil.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        nomeperfil.setForeground(new java.awt.Color(255, 255, 255));
        nomeperfil.setText("Orquestra do Maestro");
        jPanel1.add(nomeperfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 21, -1, -1));

        pontos.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        pontos.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(pontos, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 48, -1, 43));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/estrela.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 48, -1, 43));

        pontostxt.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        pontostxt.setForeground(new java.awt.Color(255, 255, 255));
        pontostxt.setText("Pontos:");
        jPanel1.add(pontostxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 48, -1, 43));

        jButton1.setBackground(new java.awt.Color(0, 178, 128));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/perfil config.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setDoubleBuffered(true);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 29, -1, 62));

        jButton2.setBackground(new java.awt.Color(0, 178, 128));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log_menor_2.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Perfil perfil = new Perfil();
        perfil.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botao_seguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_seguirActionPerformed
        if(!foiClicado) {
            foiClicado = true;
            botao_seguir.setBackground(new Color(255,255,255));
            botao_seguir.setText("Seguindo");
            seguidores.setText("127");
            
        } else {
            foiClicado = false;
            botao_seguir.setBackground(new Color(0,178,128));
            botao_seguir.setText("Seguir");
            seguidores.setText("126");
        }
    }//GEN-LAST:event_botao_seguirActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Pg1 pg1 = new Pg1();
        pg1.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Atividades atividades = new Atividades();
        atividades.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Recompensa recompensa = new Recompensa();
        recompensa.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void curtida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curtida1ActionPerformed
        ImageIcon icone_inicial = new ImageIcon(getClass().getResource("/images/heart.png"));
        ImageIcon novo_icone = new ImageIcon(getClass().getResource("/images/euodeionetbeans.png"));
        
        if(!foiClicado_1) {
            foiClicado_1 = true;
            curtida1.setIcon(novo_icone);
        } else {
            foiClicado_1 = false;
            curtida1.setIcon(icone_inicial); 
        }
    }//GEN-LAST:event_curtida1ActionPerformed

    private void curtida2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curtida2ActionPerformed
        ImageIcon icone_inicial = new ImageIcon(getClass().getResource("/images/heart.png"));
        ImageIcon novo_icone = new ImageIcon(getClass().getResource("/images/euodeionetbeans.png"));
        
        if(!foiClicado_2) {
            foiClicado_2 = true;
            curtida2.setIcon(novo_icone);
        } else {
            foiClicado_2 = false;
            curtida2.setIcon(icone_inicial); 
        }
    }//GEN-LAST:event_curtida2ActionPerformed

    private void curtida3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curtida3ActionPerformed
        ImageIcon icone_inicial = new ImageIcon(getClass().getResource("/images/heart.png"));
        ImageIcon novo_icone = new ImageIcon(getClass().getResource("/images/euodeionetbeans.png"));
        
        if(!foiClicado_3) {
            foiClicado_3 = true;
            curtida3.setIcon(novo_icone);
        } else {
            foiClicado_3 = false;
            curtida3.setIcon(icone_inicial); 
        }
    }//GEN-LAST:event_curtida3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_seguir;
    private javax.swing.JButton curtida1;
    private javax.swing.JButton curtida2;
    private javax.swing.JButton curtida3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomeperfil;
    public javax.swing.JLabel pontos;
    private javax.swing.JLabel pontostxt;
    private javax.swing.JLabel seguidores;
    // End of variables declaration//GEN-END:variables
}
